# Generated by Django 4.2.2 on 2024-07-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_remove_course_owner_remove_lesson_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="last_update_date",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата последнего обновления"
            ),
        ),
    ]
