# Generated by Django 4.2.2 on 2024-07-21 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_test", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="course_test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="knowledge_test.coursetest",
                verbose_name="Тест",
            ),
        ),
    ]
