# Generated by Django 4.2.2 on 2024-07-23 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_remove_course_owner_remove_lesson_owner_and_more"),
        ("knowledge_test", "0002_alter_question_course_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursetest",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
    ]
